version: 2
registries:
  github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com/
    token: ${{secrets.ORG_GITHUB_ACTION_TOKEN}}

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '13:00'
      timezone: US/Central
    # make dependabot PRs releasable
    commit-message:
      prefix: 'fix'
      prefix-development: 'build'
    # Ignore dev dependencies to reduce noise
    allow:
      - dependency-type: 'production'
    # Ignore patch updates to reduce noise
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    open-pull-requests-limit: 5
    registries:
      - github-packages
